### ISSUE TITLE
Can't show entire the shadow and cannot be edited.

### ISSUE THREAD

**Issue by Myerden** [championswimmer/Android-SocialButtons#7]
At first, thank you for this nice library.

My problem is, I want to add some social buttons inside the horizontal linear layout. After adding, the buttons' shadow seems like cutten, like this;

![screenshot_2017-08-24-20-04-04](https://user-images.githubusercontent.com/15304742/29679989-de125c08-890b-11e7-9769-b8a82e44137b.png)

I am trying to add spaces bottom of the buttons but I could't achive this.
I added margin, padding to each button, liner layout and scrollview orderly. But I could't fix it.
Also I can not disable the shadows. So, the shadow attribute should be added and the view size should be edited according to shadow size.

Thank you.

**Comment by championswimmer** [comment]
Increase or decrease the padding.

**Comment by championswimmer** [comment]
solved in version 1.3
